t = 'CACTGCGATTACCACTGCGATTACCACTGCGATTACCACTGCGATTACCACTGCGATTACCACTGCGATTACCACTGCGATTACCACTGCGATTACCACTGCGATTACCACTGCGATTACCACTGCGATTACCACTGCGATTACCACTGCGATTACCACTGCGATTACCACTGCGATTACCACTGCGATTACCACTGCGATTACCACTGCGATTACCACTGCGATTAC'
p = 'TGCGATTACCACTGCGATTACCACTGCGATTACCACTG'


# This does not need to be modified
p_bm = BoyerMoore(p, alphabet='ACGT')
result= boyer_moore(p, p_bm, t)

print "\n", "Results:", "\n"

for place in result:
	print str(place),